[server]
host = "0.0.0.0"
port = 25565

[server.serverlist]
motd = "&bVery Cool Minecraft Server!"

players = [
    "Join the Server now!",
    "We are waiting!"
]
max = 50

[plugins]
bukkit = true
sponge = true
path = "./plugins"
data = "./plugins/%plugin%"

[worlds]
path = "./worlds"