package com.theultimatepleb.minecraft.server.chat

import java.util.*

/**
 * Created by Sebastian Agius on 10/09/2017.
 */
data class ChatComponent(val text: String,
                         val bold: Boolean? = null,
                         val italic: Boolean? = null,
                         val strikethrough: Boolean? = null,
                         val obfuscated: Boolean? = null,
                         val color: String? = null,
                         val insertion: String? = null,
                         val clickEvent: ClickEvent? = null,
                         val hoverEvent: HoverEvent? = null,
                         val extra: Array<ChatComponent>? = null) {

    /**
     * Generated by IntelliJ
     */
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as ChatComponent

        if (text != other.text) return false
        if (bold != other.bold) return false
        if (italic != other.italic) return false
        if (strikethrough != other.strikethrough) return false
        if (obfuscated != other.obfuscated) return false
        if (insertion != other.insertion) return false
        if (clickEvent != other.clickEvent) return false
        if (hoverEvent != other.hoverEvent) return false
        if (!Arrays.equals(extra, other.extra)) return false

        return true
    }

    /**
     * Generated by IntelliJ
     */
    override fun hashCode(): Int {
        var result = text.hashCode()
        result = 31 * result + (bold?.hashCode() ?: 0)
        result = 31 * result + (italic?.hashCode() ?: 0)
        result = 31 * result + (strikethrough?.hashCode() ?: 0)
        result = 31 * result + (obfuscated?.hashCode() ?: 0)
        result = 31 * result + (insertion?.hashCode() ?: 0)
        result = 31 * result + (clickEvent?.hashCode() ?: 0)
        result = 31 * result + (hoverEvent?.hashCode() ?: 0)
        result = 31 * result + (extra?.let { Arrays.hashCode(it) } ?: 0)
        return result
    }


}