package com.theultimatepleb.minecraft.crystal

/**
 * Created by Sebastian Agius on 11/09/2017.
 */
enum class Material(isBlock: Boolean = true, isItem: Boolean = true) {
    AIR,
    STONE,
    GRANITE_STONE,
    POLISHED_GRANITE_STONE,
    DIORITE_STONE,
    POLISHED_DIORITE_STONE,
    ANDESITE_STONE,
    POLISHED_ANDESITE_STONE,
    GRASS,
    DIRT,
    COARSE_DIRT,
    PODZOL_DIRT,
    COBBLESTONE,
    OAK_PLANKS,
    SPRUCE_PLANK,
    BIRCH_PLANK,
    JUNGLE_PLANKS,
    ACACIA_PLANKS,
    DARK_OAK_PLANK,
    OAK_SAPLING,
    SPRUCE_SAPLING,
    BIRCH_SAPLING,
    JUNGLE_SAPLING,
    ACACIA_SAPLING,
    DARK_OAK_SAPLING,
    BEDROCK,
    WATER(true, false),
    STILL_WATER(true, false),
    LAVA(true, false),
    STILL_LAVA(true, false),
    SAND,
    RED_SAND,
    GRAVEL,
    GOLD_ORE,
    IRON_ORE,
    COAL_ORE,
    OAK_LOG,
    SPRUCE_LOG,
    BIRCH_LOG,
    JUNGLE_LOG,
    OAK_LEAVES,
    SPRUCE_LEAVES,
    BIRCH_LEAVES,
    JUNGLE_LEAVES,
    SPONGE,
    WET_SPONGE,
    GLASS,
    LAPIS_ORE,
    LAPIS_BLOCK,
    DISPENSER,
    SANDSTONE,
    CHISELED_SANDSTONE,
    SMOOTH_SANDSTONE,
    NOTEBLOCK,
    BED,
    GOLDEN_RAIL,
    DETECTOR_RAIL,
    STICKY_PISTON,
    WEB,
    DEAD_SHRUB_TALLGRASS,
    GRASS_TALLGRASS,
    FERN_TALLGRASS,
    DEADBUSH,
    PISTON,
    PISTON_HEAD(true, false),
    WHITE_WOOL,
    ORANGE_WOOL,
    MAGENTA_WOOL,
    LIGHT_BLUE_WOOL,
    YELLOW_WOOL,
    LIME_WOOL,
    PINK_WOOL,
    GRAY_WOOL,
    LIGHT_GRAY_WOOL,
    CYAN_WOOL,
    PURPLE_WOOL,
    BLUE_WOOL,
    BROWN_WOOL,
    GREEN_WOOL,
    RED_WOOL,
    BLACK_WOOL,
    DANDELION_FLOWER,
    POPPY_FLOWER,
    BLUE_ORCHID_FLOWER,
    ALLIUM_FLOWER,
    AZURE_BLUET_FLOWER,
    RED_TULIP_FLOWER,
    ORANGE_TULIP_FLOWER,
    WHITE_TULIP_FLOWER,
    PINK_TULIP_FLOWER,
    OXEYE_DAISY_FLOWER,
    BROWN_MUSHROOM,
    RED_MUSHROOM,
    GOLD_BLOCK,
    IRON_BLOCK,
    DOUBLE_STONE_SLAB,
    DOUBLE_SANDSTONE_SLAB,
    DOUBLE_WOODEN_SLAB,
    DOUBLE_COBBLESTONE_SLAB,
    DOUBLE_BRICK_SLAB,
    DOUBLE_STONE_BRICK_SLAB,
    DOUBLE_NETHER_BRICK_SLAB,
    DOUBLE_QUARTZ_SLAB,
    STONE_SLAB,
    SANDSTONE_SLAB,
    WOODEN_SLAB,
    COBBLESTONE_SLAB,
    BRICK_SLAB,
    STONE_BRICK_SLAB,
    NETHER_BRICK_SLAB,
    QUARTZ_SLAB,
    BRICK_BLOCK,
    TNT,
    BOOKSHELF,
    MOSSY_COBBLESTONE,
    OBSIDIAN,
    TORCH,
    FIRE(true, false),
    MOB_SPAWNER,
    OAK_STAIRS,
    CHEST,
    REDSTONE_WIRE(true, false),
    DIAMOND_ORE,
    DIAMOND_BLOCK,
    CRAFTING_TABLE,
    WHEAT,
    FARMLAND(true, false),
    FURNACE,
    LIT_FURNACE(true, false),
    STANDING_SIGN(true, false),
    WOODEN_DOOR,
    LADDER,
    RAIL,
    STONE_STAIRS,
    WALL_SIGN(true, false),
    LEVER,
    STONE_PRESSURE_PLATE,
    IRON_DOOR,
    WOODEN_PRESSURE_PLATE,
    REDSTONE_ORE,
    LIT_REDSTONE_ORE(true, false),
    UNLIT_REDSTONE_TORCH(true, false),
    REDSTONE_TORCH,
    STONE_BUTTON,
    SNOW_LAYER,
    ICE,
    SNOW,
    CACTUS,
    CLAY,
    REEDS,
    JUKEBOX,
    FENCE,
    PUMPKIN,
    NETHERRACK,
    SOUL_SAND,
    GLOWSTONE,
    PORTAL(true, false),
    LIT_PUMPKIN,
    CAKE,
    UNPOWERED_REPEATER(true, false),
    POWERED_REPEATER(true, false),
    WHITE_STAINED_GLASS,
    ORANGE_STAINED_GLASS,
    MAGENTA_STAINED_GLASS,
    LIGHT_BLUE_STAINED_GLASS,
    YELLOW_STAINED_GLASS,
    LIME_STAINED_GLASS,
    PINK_STAINED_GLASS,
    GRAY_STAINED_GLASS,
    LIGHT_GRAY_STAINED_GLASS,
    CYAN_STAINED_GLASS,
    PURPLE_STAINED_GLASS,
    BLUE_STAINED_GLASS,
    BROWN_STAINED_GLASS,
    GREEN_STAINED_GLASS,
    RED_STAINED_GLASS,
    BLACK_STAINED_GLASS,
    TRAPDOOR,
    STONE_MONSTER_EGG,
    COBBLESTONE_MONSTER_EGG,
    STONE_BRICK_MONSTER_EGG,
    MOSSY_STONE_BRICK_MONSTER_EGG,
    CRACKED_STONE_BRICK_MONSTER_EGG,
    CHISELED_STONE_BRICK_MONSTER_EGG,
    STONEBRICK,
    MOSSY_STONEBRICK,
    CRACKED_STONEBRICK,
    BROWN_MUSHROOM_BLOCK,
    RED_MUSHROOM_BLOCK,
    IRON_BARS,
    GLASS_PANE,
    MELON_BLOCK,
    PUMPKIN_STEM(true, false),
    MELON_STEM(true, false),
    VINE,
    FENCE_GATE,
    BRICK_STAIRS,
    STONE_BRICK_STAIRS,
    MYCELLIUM,
    WATERLILLY,
    NETHER_BRICK,
    NETHER_BRICK_FENCE,
    NETHER_BRICK_STAIRS,
    NETHER_WART,
    ENCHANTING_TABLE,
    BREWING_STAND,
    CAULDRON,
    END_PORTAL(true, false),
    END_PORTAL_FRAME,
    END_STONE,
    DRAGON_EGG,
    REDSTONE_LAMP,
    LIT_REDSTONE_LAMP(true, false),
    OAK_DOUBLE_WOODEN_SLAB,
    SPRUCE_DOUBLE_WOODEN_SLAB,
    BIRCH_DOUBLE_WOODEN_SLAB,
    JUNGLE_DOUBLE_WOODEN_SLAB,
    ACACIA_DOUBLE_WOODEN_SLAB,
    DARK_OAK_DOUBLE_WOODEN_SLAB,
    OAK_WOODEN_SLAB,
    SPRUCE_WOODEN_SLAB,
    BIRCH_WOODEN_SLAB,
    JUNGLE_WOODEN_SLAB,
    ACACIA_WOODEN_SLAB,
    DARK_OAK_WOODEN_SLAB,
    COCOA,
    SANDSTONE_STAIRS,
    EMERALD_ORE,
    ENDER_CHEST,
    TRIPWIRE_HOOK,
    EMERALD_BLOCK,
    SPRUCE_STAIRS,
    BIRCH_STAIRS,
    JUNGLE_STAIRS,
    COMMAND_BLOCK,
    BEACON,
    COBBLESTONE_WALL,
    MOSSY_COBBLESTONE_WALL,
    FLOWER_POT,
    CARROTS(true, false),
    POTATOES(true, false),
    WOODEN_BUTTON,
    SKULL,
    ANVIL,
    TRAPPED_CHEST,
    LIGHT_WEIGHTED_PRESSURE_PLATE,
    HEAVY_WEIGHTED_PRESSURE_PLATE,
    UNPOWERED_COMPARATOR(true, false),
    POWERED_COMPARATOR(true, false),
    DAYLIGHT_DETECTOR,
    REDSTONE_BLOCK,
    QUARTZ_ORE,
    HOPPER,
    QUARTZ_BLOCK,
    CHISELED_QUARTZ_BLOCK,
    PILLAR_QUARTZ_BLOCK,
    QUARTZ_STAIRS,
    ACTIVATOR_RAIL,
    DROPPER,
    WHITE_STAINED_HARDENED_CLAY,
    ORANGE_STAINED_HARDENED_CLAY,
    MAGENTA_STAINED_HARDENED_CLAY,
    LIGHT_BLUE_STAINED_HARDENED_CLAY,
    YELLOW_STAINED_HARDENED_CLAY,
    LIME_STAINED_HARDENED_CLAY,
    PINK_STAINED_HARDENED_CLAY,
    GRAY_STAINED_HARDENED_CLAY,
    LIGHT_GRAY_STAINED_HARDENED_CLAY,
    CYAN_STAINED_HARDENED_CLAY,
    PURPLE_STAINED_HARDENED_CLAY,
    BLUE_STAINED_HARDENED_CLAY,
    BROWN_STAINED_HARDENED_CLAY,
    GREEN_STAINED_HARDENED_CLAY,
    RED_STAINED_HARDENED_CLAY,
    BLACK_STAINED_HARDENED_CLAY,
    WHITE_STAINED_GLASS_PANE,
    ORANGE_STAINED_GLASS_PANE,
    MAGENTA_STAINED_GLASS_PANE,
    LIGHT_BLUE_STAINED_GLASS_PANE,
    YELLOW_STAINED_GLASS_PANE,
    LIME_STAINED_GLASS_PANE,
    PINK_STAINED_GLASS_PANE,
    GRAY_STAINED_GLASS_PANE,
    LIGHT_GRAY_STAINED_GLASS_PANE,
    CYAN_STAINED_GLASS_PANE,
    PURPLE_STAINED_GLASS_PANE,
    BLUE_STAINED_GLASS_PANE,
    BROWN_STAINED_GLASS_PANE,
    GREEN_STAINED_GLASS_PANE,
    RED_STAINED_GLASS_PANE,
    BLACK_STAINED_GLASS_PANE,
    ACACIA_LEAVES2,
    DARK_OAK_LEAVES2,
    ACACIA_LOG2,
    DARK_OAK_LOG2,
    SLIME,
    BARRIER,
    IRON_TRAPDOOR,
    PRISMARINE,
    PRISMARINE_BRICKS,
    DARK_PRISMARINE,
    SEA_LANTERN,
    HAY_BLOCK,
    WHITE_CARPET,
    ORANGE_CARPET,
    MAGENTA_CARPET,
    LIGHT_BLUE_CARPET,
    YELLOW_CARPET,
    LIME_CARPET,
    PINK_CARPET,
    GRAY_CARPET,
    LIGHT_GRAY_CARPET,
    CYAN_CARPET,
    PURPLE_CARPET,
    BLUE_CARPET,
    BROWN_CARPET,
    GREEN_CARPET,
    RED_CARPET,
    BLACK_CARPET,
    HARDENED_CLAY,
    COAL_BLOCK,
    PACKED_ICE,
    SUNFLOWER_DOUBLE_PLANT,
    LILAC_DOUBLE_PLANT,
    DOUBLE_TALLGRASS_DOUBLE_PLANT,
    LARGE_FERN_DOUBLE_PLANT,
    ROSE_BUSH_DOUBLE_PLANT,
    PEONY_DOUBLE_PLANT,
    STANDING_BANNER(true, false),
    WALL_BANNER(true, false),
    DAYLIGHT_DETECTOR_INVERTED,
    RED_SANDSTONE,
    CHISELED_RED_SANDSTONE,
    SMOOTH_RED_SANDSTONE,
    RED_SANDSTONE_STAIRS,
    RED_SANDSTONE_DOUBLE_STONE_SLAB2,
    RED_SANDSTONE_STONE_SLAB2,
    SPRUCE_FENCE_GATE,
    BIRCH_FENCE_GATE,
    JUNGLE_FENCE_GATE,
    DARK_OAK_FENCE_GATE,
    ACACIA_FENCE_GATE,
    SPRUCE_FENCE,
    BIRCH_FENCE,
    JUNGLE_FENCE,
    DARK_OAK_FENCE,
    ACACIA_FENCE,
    SPRUCE_DOOR,
    BIRCH_DOOR,
    JUNGLE_DOOR,
    DARK_OAK_DOOR,
    ACACIA_DOOR,
    END_ROD,
    CHORUS_PLANT,
    CHORUS_FLOWER,
    PURPUR_BLOCK,
    PURPUR_PILLAR,
    PURPUR_STAIRS,
    PURPUR_DOUBLE_SLAB,
    PURPUR_SLAB,
    END_BRICKS,
    BEETROOTS(true, false),
    GRASS_PATH(true, false),
    END_GATEWAY(true, false),
    REPEATING_COMMAND_BLOCK,
    CHAIN_COMMAND_BLOCK,
    FROSTED_ICE,
    MAGMA,
    NETHER_WART_BLOCK,
    RED_NETHER_BRICK,
    BONE_BLOCK,
    STRUCTURE_VOID,
    OBSERVER,
    WHITE_SHULKER_BOX,
    ORANGE_SHULKER_BOX,
    MAGENTA_SHULKER_BOX,
    LIGHT_BLUE_SHULKER_BOX,
    YELLOW_SHULKER_BOX,
    LIME_SHULKER_BOX,
    PINK_SHULKER_BOX,
    GRAY_SHULKER_BOX,
    LIGHT_GRAY_SHULKER_BOX,
    CYAN_SHULKER_BOX,
    PURPLE_SHULKER_BOX,
    BLUE_SHULKER_BOX,
    BROWN_SHULKER_BOX,
    GREEN_SHULKER_BOX,
    RED_SHULKER_BOX,
    BLACK_SHULKER_BOX,
    WHITE_GLAZED_TERRACOTTA,
    ORANGE_GLAZED_TERRACOTTA,
    MAGENTA_GLAZED_TERRACOTTA,
    LIGHT_BLUE_GLAZED_TERRACOTTA,
    YELLOW_GLAZED_TERRACOTTA,
    LIME_GLAZED_TERRACOTTA,
    PINK_GLAZED_TERRACOTTA,
    GRAY_GLAZED_TERRACOTTA,
    LIGHT_GRAY_GLAZED_TERRACOTTA,
    CYAN_GLAZED_TERRACOTTA,
    PURPLE_GLAZED_TERRACOTTA,
    BLUE_GLAZED_TERRACOTTA,
    BROWN_GLAZED_TERRACOTTA,
    GREEN_GLAZED_TERRACOTTA,
    RED_GLAZED_TERRACOTTA,
    BLACK_GLAZED_TERRACOTTA,
    WHITE_CONCRETE,
    ORANGE_CONCRETE,
    MAGENTA_CONCRETE,
    LIGHT_BLUE_CONCRETE,
    YELLOW_CONCRETE,
    LIME_CONCRETE,
    PINK_CONCRETE,
    GRAY_CONCRETE,
    LIGHT_GRAY_CONCRETE,
    CYAN_CONCRETE,
    PURPLE_CONCRETE,
    BLUE_CONCRETE,
    BROWN_CONCRETE,
    GREEN_CONCRETE,
    RED_CONCRETE,
    BLACK_CONCRETE,
    WHITE_CONCRETE_POWDER,
    ORANGE_CONCRETE_POWDER,
    MAGENTA_CONCRETE_POWDER,
    LIGHT_BLUE_CONCRETE_POWDER,
    YELLOW_CONCRETE_POWDER,
    LIME_CONCRETE_POWDER,
    PINK_CONCRETE_POWDER,
    GRAY_CONCRETE_POWDER,
    LIGHT_GRAY_CONCRETE_POWDER,
    CYAN_CONCRETE_POWDER,
    PURPLE_CONCRETE_POWDER,
    BLUE_CONCRETE_POWDER,
    BROWN_CONCRETE_POWDER,
    GREEN_CONCRETE_POWDER,
    RED_CONCRETE_POWDER,
    BLACK_CONCRETE_POWDER,
    STRUCTURE_BLOCK,
    IRON_SHOVEL(false, true),
    IRON_PICKAXE(false, true),
    IRON_AXE(false, true),
    FLINT_AND_STEEL(false, true),
    APPLE(false, true),
    BOW(false, true),
    ARROW(false, true),
    COAL(false, true),
    CHARCOAL(false, true),
    DIAMOND(false, true),
    IRON_INGOT(false, true),
    GOLD_INGOT(false, true),
    IRON_SWORD(false, true),
    WOODEN_SWORD(false, true),
    WOODEN_SHOVEL(false, true),
    WOODEN_PICKAXE(false, true),
    WOODEN_AXE(false, true),
    STONE_SWORD(false, true),
    STONE_SHOVEL(false, true),
    STONE_PICKAXE(false, true),
    STONE_AXE(false, true),
    DIAMOND_SWORD(false, true),
    DIAMOND_SHOVEL(false, true),
    DIAMOND_PICKAXE(false, true),
    DIAMOND_AXE(false, true),
    STICK(false, true),
    BOWL(false, true),
    MUSHROOM_STEW(false, true),
    GOLDEN_SWORD(false, true),
    GOLDEN_SHOVEL(false, true),
    GOLDEN_PICKAXE(false, true),
    GOLDEN_AXE(false, true),
    STRING_FEATHER(false, true),
    GUNPOWDER(false, true),
    WOODEN_HOE(false, true),
    STONE_HOE(false, true),
    IRON_HOE(false, true),
    DIAMOND_HOE(false, true),
    GOLD_HOE(false, true),
    WHEAT_SEEDS(false, true),
    BREAD(false, true),
    LEATHER_HELMET(false, true),
    LEATHER_CHESTPLATE(false, true),
    LEATHER_LEGGINGS(false, true),
    LEATHER_BOOTS(false, true),
    CHAINMAIL_HELMET(false, true),
    CHAINMAIL_CHESTPLATE(false, true),
    CHAINMAIL_LEGGINGS(false, true),
    CHAINMAIL_BOOTS(false, true),
    IRON_HELMET(false, true),
    IRON_CHESTPLATE(false, true),
    IRON_LEGGINGS(false, true),
    IRON_BOOTS(false, true),
    DIAMOND_HELMET(false, true),
    DIAMOND_CHESTPLATE(false, true),
    DIAMOND_LEGGINGS(false, true),
    DIAMOND_BOOTS(false, true),
    GOLD_HELMET(false, true),
    GOLD_CHESTPLATE(false, true),
    GOLD_LEGGINGS(false, true),
    GOLD_BOOTS(false, true),
    FLINT(false, true),
    PORKCHOP(false, true),
    COOKED_PORKCHOP(false, true),
    PAINTING(false, true),
    GOLDEN_APPLE(false, true),
    ENCHANTED_GOLDEN_APPLE(false, true),
    SIGN(false, true),
    BUCKET(false, true),
    WATER_BUCKET(false, true),
    LAVA_BUCKET(false, true),
    MINECART(false, true),
    SADDLE(false, true),
    REDSTONE(false, true),
    SNOWBALL(false, true),
    BOAT(false, true),
    LEATHER(false, true),
    MILK_BUCKET(false, true),
    BRICK(false, true),
    CLAY_BALL(false, true),
    PAPER(false, true),
    BOOK(false, true),
    SLIME_BALL(false, true),
    CHEST_MINECART(false, true),
    FURNACE_MINECART(false, true),
    EGG(false, true),
    COMPASS(false, true),
    FISHING_ROD(false, true),
    CLOCK(false, true),
    GLOWSTONE_DUST(false, true),
    FISH(false, true),
    SALMON_FISH(false, true),
    COOKED_FISH(false, true),
    SALMON_COOKED_FISH(false, true),
    INK_SACK_DYE(false, true),
    ROSE_RED_DYE(false, true),
    CACTUS_GREEN_DYE(false, true),
    COCO_BEANS_DYE(false, true),
    LAPIS_LAZULI_DYE(false, true),
    PURPLE_DYE(false, true),
    CYAN_DYE(false, true),
    LIGHT_GRAY_DYE(false, true),
    GRAY_DYE(false, true),
    PINK_DYE(false, true),
    LIME_DYE(false, true),
    DANDELION_YELLOW_DYE(false, true),
    LIGHT_BLUE_DYE(false, true),
    MAGENTA_DYE(false, true),
    ORANGE_DYE(false, true),
    BONE_MEAL_DYE(false, true),
    BONE(false, true),
    SUGAR(false, true),
    REPEATER(false, true),
    COOKIE(false, true),
    FILLED_MAP(false, true),
    SHEARS(false, true),
    MELON(false, true),
    PUMPKIN_SEEDS(false, true),
    MELON_SEEDS(false, true),
    BEEF(false, true),
    COOKED_BEEF(false, true),
    CHICKEN(false, true),
    COOKED_CHICKEN(false, true),
    ROTTEN_FLESH(false, true),
    ENDER_PEARL(false, true),
    BLAZE_ROD(false, true),
    GHAST_TEAR(false, true),
    GOLD_NUGGET(false, true),
    POTION(false, true),
    GLASS_BOTTLE(false, true),
    SPIDER_EYE(false, true),
    FERMENTED_SPIDER_EYE(false, true),
    BLAZE_POWDER(false, true),
    MAGMA_CREAM(false, true),
    ENDER_EYE(false, true),
    SPECKLED_MELON(false, true),
    ELDER_GUARDIAN_SPAWN_EGG(false, true),
    WITHER_SKELETON_SPAWN_EGG(false, true),
    STRAY_SPAWN_EGG(false, true),
    HUSK_SPAWN_EGG(false, true),
    ZOMBIE_VILLAGER_SPAWN_EGG(false, true),
    SKELETON_HORSE_SPAWN_EGG(false, true),
    ZOMBIE_HORSE_SPAWN_EGG(false, true),
    DONKEY_SPAWN_EGG(false, true),
    MULE_SPAWN_EGG(false, true),
    EVOKER_SPAWN_EGG(false, true),
    VEX_SPAWN_EGG(false, true),
    VINDICATOR_SPAWN_EGG(false, true),
    CREEPER_SPAWN_EGG(false, true),
    SKELETON_SPAWN_EGG(false, true),
    SPIDER_SPAWN_EGG(false, true),
    ZOMBIE_SPAWN_EGG(false, true),
    SLIME_SPAWN_EGG(false, true),
    GHAST_SPAWN_EGG(false, true),
    ZOMBIE_PIGMAN_SPAWN_EGG(false, true),
    ENDERMAN_SPAWN_EGG(false, true),
    CAVE_SPIDER_SPAWN_EGG(false, true),
    SILVERFISH_SPAWN_EGG(false, true),
    BLAZE_SPAWN_EGG(false, true),
    MAGMA_CUBE_SPAWN_EGG(false, true),
    BAT_SPAWN_EGG(false, true),
    WITCH_SPAWN_EGG(false, true),
    ENDERMITE_SPAWN_EGG(false, true),
    GUARDIAN_SPAWN_EGG(false, true),
    SHULKER_SPAWN_EGG(false, true),
    PIG_SPAWN_EGG(false, true),
    SHEEP_SPAWN_EGG(false, true),
    COW_SPAWN_EGG(false, true),
    CHICKEN_SPAWN_EGG(false, true),
    SQUID_SPAWN_EGG(false, true),
    WOLF_SPAWN_EGG(false, true),
    MOOSHROOM_SPAWN_EGG(false, true),
    OCELOT_SPAWN_EGG(false, true),
    HORSE_SPAWN_EGG(false, true),
    RABBIT_SPAWN_EGG(false, true),
    POLAR_BEAR_SPAWN_EGG(false, true),
    LLAMA_SPAWN_EGG(false, true),
    VILLAGER_SPAWN_EGG(false, true),
    EXPERIENCE_BOTTLE(false, true),
    FIRE_CHARGE(false, true),
    WRITABLE_BOOK(false, true),
    WRITTEN_BOOK(false, true),
    EMERALD(false, true),
    ITEM_FRAME(false, true),
    CARROT(false, true),
    POTATO(false, true),
    BAKED_POTATO(false, true),
    POISONOUS_POTATO(false, true),
    MAP(false, true),
    GOLDEN_CARROT(false, true),
    SKELETON_SKULL(false, true),
    WITHER_SKELETON_SKULL(false, true),
    ZOMBIE_SKULL(false, true),
    HUMAN_SKULL(false, true),
    CREEPER_SKULL(false, true),
    DRAGON_SKULL(false, true),
    CARROT_ON_A_STICK(false, true),
    NETHER_STAR(false, true),
    PUMPKIN_PIE(false, true),
    FIREWORKS(false, true),
    FIREWORK_CHARGE(false, true),
    ENCHANTED_BOOK(false, true),
    COMPARATOR(false, true),
    NETHERBRICK(false, true),
    QUARTZ(false, true),
    TNT_MINECART(false, true),
    HOPPER_MINECART(false, true),
    PRISMARINE_SHARD(false, true),
    PRISMARINE_CRYSTALS(false, true),
    RABBIT(false, true),
    COOKED_RABBIT(false, true),
    RABBIT_STEW(false, true),
    RABBIT_FOOT(false, true),
    ARMOR_STAND(false, true),
    IRON_HORSE_ARMOR(false, true),
    GOLDEN_HORSE_ARMOR(false, true),
    DIAMOND_HORSE_ARMOR(false, true),
    LEAD(false, true),
    NAME_TAG(false, true),
    COMMAND_BLOCK_MINECART(false, true),
    MUTTON(false, true),
    COOKED_MUTTON(false, true),
    BANNER(false, true),
    CHROUS_FRUIT(false, true),
    POPPED_CHORUS_FRUIT(false, true),
    BEETROOT(false, true),
    BEETROOT_SEEDS(false, true),
    BEETROOT_SOUP(false, true),
    DRAGON_BREATH(false, true),
    SPLASH_POTION(false, true),
    SPECTRAL_ARROW(false, true),
    TIPPED_ARROW(false, true),
    LINGERING_POTION(false, true),
    SHIELD(false, true),
    ELYTRA(false, true),
    SPRUCE_BOAT(false, true),
    BIRCH_BOAT(false, true),
    JUNGLE_BOAT(false, true),
    ACACIA_BOAT(false, true),
    DARK_OAK_BOAT(false, true),
    TOTEM_OF_UNDYING(false, true),
    SHULKER_SHELL(false, true),
    IRON_NUGGET(false, true),
    RECORD_13(false, true),
    RECORD_CAT(false, true),
    RECORD_BLOCKS(false, true),
    RECORD_CHIRP(false, true),
    RECORD_FAR(false, true),
    RECORD_MALL(false, true),
    RECORD_MELLOHI(false, true),
    RECORD_STAL(false, true),
    RECORD_STRAD(false, true),
    RECORD_WARD(false, true),
    RECORD_11(false, true),
    RECORD_WAIT(false, true);

    fun nameL(): String = name.toLowerCase()
}